version: '3.9'
name: faculty-hours-faculty
services:
  web:
    env_file:
      - .env
    build:
      context: ..
      dockerfile: ./.docker/Dockerfile
    volumes:
      - ../:/app/
    ports:
      - "8100:8100"
    networks:
      - faculty_network
      - common_network
  db:
    image: postgres:13
    container_name: "fh-app-faculty-db"
    env_file:
      - .env
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data/:Z
    expose:
      - 5432
    networks:
      - faculty_network
networks:
  faculty_network:
    driver: bridge
  common_network:
    external: true
volumes:
  postgres_data:
